### ISSUE TITLE
defineConfig -> loadCustomStore types expect Promise<undefined>

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3504] opened 2023-01-09 19:02 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When trying to set up an external media store, the types for defineConfig -> loadCustomStore are wrong.
It expects a function that returns Promise<undefined>.

### Reproduction

https://github.com/tinacms/tina.io/pull/1464/files#diff-720ba15b7b4d6da8c5c94d84fa4d7e35dc86a5bcbe8af231aef990eb154e2f7aR13

### Steps to reproduce

Remove @ts-ignore above line

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 490.65 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/Documents/forestry/tinacms-site-next/node_modules/.bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 88.0.1
    Safari: 15.6.1
  npmPackages:
    @tinacms/auth: ^1.0.0 => 1.0.0 
    @tinacms/cli: 1.0.5 => 1.0.5 
    @tinacms/datalayer:  0.2.3 
    @tinacms/graphql:  0.60.0 
    tinacms: 1.1.2 => 1.1.2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by coreyaus** [comment] 2023-04-25 23:51
Hey @logan-anderson - just a heads up that I think you may have resolved this issue via PR #3818 (i.e. this issue is a possible duplicate of #3799). I might be wrong though but just flagging while I noticed in case this issue can also be closed 👍

**Closed** 2023-09-03 08:48 UTC
Labels: bug, good first issue, wontfix
