### ISSUE TITLE
Can't delete the last item in a list of an object field

### ISSUE THREAD

**Issue by twittkopf** [tinacms/tinacms#4161] opened 2023-08-22 19:52 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

The `home` collection (it's a single document collection) contains a list field `curatedPosts` that references the `post` collection. Deleting the last list item in `curatedPosts` seems to be impossible. Even though the interface updates at first, the `index.mdx` file is not updated and after a full refresh, the list item is still there.

### Reproduction

https://github.com/twittkopf/tina-delete-last-list-item

### Steps to reproduce

With the dev server running:

1. Open localhost:3000/admin/index.html and navigate to the "Homepage" collection
2. In the "Related Posts" section, click on the only item's trash bin icon to delete it.
3. Click "Save" to save the changes.
4. Reload the page to see the item is still there.

### System Info

```shell
System:
  OS: macOS 11.6.2
  CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  Memory: 1.66 GB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
  npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  pnpm: 8.6.1 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
Browsers:
  Chrome: 116.0.5845.96
  Safari: 15.2
npmPackages:
  @tinacms/cli: ^1.5.29 => 1.5.29 
  tinacms: ^1.5.20 => 1.5.20
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment] 2023-08-28 13:39
Looks like a duplicate of #4091 (Although I'll adjust the title since it seems it's not limited to tag fields)

**Closed by jamespohalloran** 2023-08-28 13:39 UTC
Labels: bug
