### ISSUE TITLE
Blocks editor should be sticky so it is always visible

### ISSUE THREAD

**Issue by JeffersonBledsoe** [tinacms/tinacms#541] opened 2019-12-17 10:51 UTC
## Description
When editing a longer block such as the body in a post on the Grande starter, the toolbar is not visible as the position is fixed to the top of the block. 

### Steps to reproduce

- Open the Grande starter
- Go to `http://localhost:8000/blog/introducing-tina-grande` to open a blog post
- Open the editor interface
- Scroll down the page

### Expected result
- I should still be able to see the WYSIWYG editor bar

### Actual result
- The WYSIWYG editor bar is off-screen

#### Tinacms Package Versions
```
gatsby-plugin-tinacms@0.1.16
@tinacms/core@0.5.0
tinacms@0.10.0
@tinacms/fields@0.1.16
@tinacms/icons@0.3.9
@tinacms/react-core@0.2.0
@tinacms/styles@0.1.0
gatsby-tinacms-git@0.2.14
@tinacms/api-git@0.4.6
@tinacms/git-client@0.4.1
gatsby-tinacms-json@0.8.0
gatsby-tinacms-remark@0.6.0
@tinacms/form-builder@0.2.8
```

**Comment by JeffersonBledsoe** [comment] 2019-12-17 10:56
I'm more than happy to take a shot at this :)

**Comment by ncphillips** [comment] 2019-12-17 11:11
Thanks @JeffersonBledsoe!

This is actually Duplicate of #425 and There’s an open PR for it in #528 . 
There’s a couple changes requested though and @weibenfalk is busy. Maybe he would like a hand?

**Comment by JeffersonBledsoe** [comment] 2019-12-17 11:11
My bad, I missed that issue!

**Closed by ncphillips** 2019-12-17 11:11 UTC
Labels: bug

**Comment by ncphillips** [comment] 2019-12-17 11:16
All good 🙂
