### ISSUE TITLE
✨ Tina Collection Search

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tinacms#4673] opened 2024-07-24 01:11 UTC
cc: @landonmaxwell 

We are trying to edit the Querying Content 'Overview' file on the tina.io/docs https://tina.io/docs/data-fetching/overview/

As an admin, i click the hamburger icon in the top left, under collections i click docs, and then search for 'overview'.

I see alot of overview files, because these all live under different directories. But how can i tell the difference? 

🎯 **Expected Solution**

There is a little more information provided about each file in the search (i.e parent directory) 

<img width="1319" alt="Screenshot 2024-07-24 at 11 10 12 AM" src="https://github.com/user-attachments/assets/e5f468e9-9149-4140-b2cd-41beaf9980bd">

**Comment by bradystroud** [comment] 2024-07-24 01:41
Closing as a duplicate of https://github.com/tinacms/tinacms/issues/4667

**Closed by bradystroud** 2024-07-24 01:41 UTC
