### ISSUE TITLE
useJsonForm hook is not working

### ISSUE THREAD

**Issue by SamuelVera** [tinacms/tinacms#380] opened 2019-10-26 16:03 UTC
## Description

useJsonForm hook doesnt renders the form based on a local Json file.
Console displays error Unexpected end of JSON input.

### Expected result

The form should be rendered and fields should be editable.

### Actual result

Data is retrieved normally from the json file.

Sidebar displays 'Welcome to Tina!' message.

Console displays error: 
FAILED SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at index.js:72

### Environment

Node: 11.15.0 (Have also tried with 12.x and 10.x with no results)
npm: 6.5.0
OS: Windows 10
Dependencies on the project.
```
"dependencies": {
    "@kennethormandy/react-fittext": "^0.6.0",
    "firebase": "^6.4.2",
    "gatsby": "^2.13.67",
    "gatsby-image": "^2.2.8",
    "gatsby-plugin-manifest": "^2.2.5",
    "gatsby-plugin-offline": "^2.2.6",
    "gatsby-plugin-react-helmet": "^3.1.3",
    "gatsby-plugin-sass": "^2.1.12",
    "gatsby-plugin-sharp": "^2.2.12",
    "gatsby-plugin-tinacms": "^0.1.7",
    "gatsby-source-filesystem": "^2.1.33",
    "gatsby-source-firebase": "^1.0.0",
    "gatsby-source-firestore": "^1.0.3",
    "gatsby-tinacms-git": "^0.2.4",
    "gatsby-tinacms-json": "^0.4.0",
    "gatsby-transformer-json": "^2.2.15",
    "gatsby-transformer-sharp": "^2.2.6",
    "node-sass": "^4.12.0",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-helmet": "^5.2.1",
    "react-media": "^1.9.2",
    "react-responsive": "^7.0.0",
    "react-responsive-modal": "^4.0.1",
    "react-scrollspy": "^3.4.0",
    "react-textfit": "^1.1.0",
    "react-waypoint": "^9.0.2"
  },
```

### gatsby-config plugins array:

```
plugins: [  `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-sass`,
    `gatsby-tinacms-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data`,
        name: "data",
      },
    },
    "gatsby-transformer-json",
    {
      resolve: "gatsby-plugin-tinacms",
      options: {
        sidebar: {
          position: "float",
        },
        plugins: [
          "gatsby-tinacms-git", "gatsby-tinacms-json"
          // We'll add some Tinacms plugins in the next step.
        ],
      },
    },
]
```

### React function component with the hook.

```
import React from "react"
import { useStaticQuery, graphql } from "gatsby"
import { useJsonForm } from "gatsby-tinacms-json"

const Home = () => {
  const homeJson = useStaticQuery(graphql`
    query MyQuery {
      dataJson {
        id
        textLeft
        textRight
        fileRelativePath
        rawJson
      }
    }
  `)

  console.log(homeJson.dataJson)
  const [homeData] = useJsonForm(homeJson.dataJson
    , {
    fields: [
      { component: "textarea", name: "rawJson.textLeft", label: "Home left text" },
      { component: "textarea", name: "rawJson.textRight", label: "Home right text" },
    ],
  }
  )


  // console.log(homeJson)
  return (
    <>
      <div className="home__title">
        <h1>
          A bigger <br />
          <span className="green bold">Lorem</span>
        </h1>
      </div>
      <div className="home__subtitle">
        <h2>
          We aim at a world <br /> where climate change&nbsp; <br />
          <span className="green">Lorem</span>
        </h2>
      </div>
      <div className="home__content">
        <div className="home__content-1">
          <p>{homeData.textLeft}</p>
        </div>
        <div className="home__content-2">
          <p>{homeData.textRight}</p>
        </div>
      </div>
    </>
  )
}

export default Home

```

### Json local file

```
{
  "textLeft": "Text template",
  "textRight": "Text template 2"
}

```
## Extra

This is the function where the FAILED SyntaxError: Unexpected end of JSON input is generated.
Its on the gatsby-tinacms-json package.

```
function useJsonForm(jsonNode, formOptions) {
    if (formOptions === void 0) { formOptions = {}; }
    if (!jsonNode || process.env.NODE_ENV === 'production') {
        return [{}, null];
    }
    validateJsonNode(jsonNode);
    var cms = react_tinacms_1.useCMS();
    var label = jsonNode.fileRelativePath;
    var id = jsonNode.fileRelativePath;
    /**
     * The state of the JsonForm, generated from the contents of the
     * Json file currently on disk. This state will contain any
     * un-committed changes in the Json file.
     */
    var valuesOnDisk = react_1.useMemo(function () { return ({
        jsonNode: jsonNode,
        rawJson: JSON.parse(jsonNode.rawJson),
    }); }, [jsonNode]);
    /**
     * The state of the JsonForm, generated from the contents of the
     * Json file at the HEAD of this git branch.
     */
    var _a = react_1.useState(), valuesInGit = _a[0], setValuesInGit = _a[1];
    react_1.useEffect(function () {
        cms.api.git
            .show(id) // Load the contents of this file at HEAD
            .then(function (git) {
            // Parse the JSON into a JsonForm data structure and store it in state.
            var rawJson = JSON.parse(git.content); //ERROR IS ORIGINATED HERE
            setValuesInGit({ jsonNode: jsonNode, rawJson: rawJson });
        })
            .catch(function (e) {
            console.log('FAILED', e);
        });
    }, [id]);
    var fields = formOptions.fields || generateFields(valuesOnDisk.rawJson);
    // TODO: This may not be necessary.
    fields.push({ name: 'jsonNode', component: null });
    var _b = react_tinacms_1.useCMSForm(__assign({ id: id,
        label: label, initialValues: valuesInGit, fields: fields,
        onSubmit: function (data) {
            return cms.api.git.onSubmit({
                files: [data.fileRelativePath],
                message: data.__commit_message || 'Tina commit',
                name: data.__commit_name,
                email: data.__commit_email,
            });
        },
        reset: function () {
            return cms.api.git.reset({ files: [id] });
        } }, formOptions), 
    // The Form will be updated if these values change.
    { values: valuesOnDisk, label: label, fields: fields }), values = _b[0], form = _b[1];
    var writeToDisk = react_1.useCallback(function (formState) {
        var _a = formState.values.rawJson, fileRelativePath = _a.fileRelativePath, rawJson = _a.rawJson, data = __rest(_a, ["fileRelativePath", "rawJson"]);
        cms.api.git.onChange({
            fileRelativePath: formState.values.jsonNode.fileRelativePath,
            content: JSON.stringify(data, null, 2),
        });
    }, []);
    react_tinacms_1.useWatchFormValues(form, writeToDisk);
    return [jsonNode, form];
}
```

 `var rawJson = JSON.parse(git.content);` is the line of code of that function that throws the error.

**Comment by ncphillips** [comment] 2019-10-28 21:04
Thanks for the report @SamuelVera. Is the repo where this is happening publicly available?

**Comment by SamuelVera** [comment] 2019-10-28 21:23
The repo isnt publicly available. I'll update the packages later and see if the problem gets fixed.

Thanks for you response!!

**Comment by SamuelVera** [comment] 2019-10-28 23:58
Just updated the packages. The problem is still there.

**Comment by ncphillips** [comment] 2019-10-29 15:43
Is the site in a subdirectory? If yes take a look at how to [configure](https://tinacms.org/docs/gatsby/configure-git-plugin) your site for that.

If not, could you add me to the repo, or create an anonymized public fork? That would be super helpful.

**Comment by SamuelVera** [comment] 2019-10-29 21:10
I'll check those docs. Also just sent you an invitation to a private repo with the project

**Comment by SamuelVera** [comment] 2019-10-29 21:11
I'll check those docs. Also just sent you an invitation to a private repo with the project. @ncphillips

**Comment by SamuelVera** [comment] 2019-10-30 13:55
I implemented the config for the git backend but just realized that the fileRelativePath field of the .json file that's queried by graphql is returning "C:/Users/samue/Desktop/Aether/Nexwell/NexwellFront/src/data/Home.json" an Absolute path, that isnt supposed to be like that, right?

**Comment by ncphillips** [comment] 2019-11-14 15:47
Hey @SamuelVera has there been any update on this issue? 

I still have not heard of this happening at other times.

**Comment by ncphillips** [comment] 2019-12-03 15:08
I'm going to close this issue for now as I have not heard any other reports, and cannot reproduce the problem

**Comment by jarodpeachey** [comment] 2020-01-14 01:02
Hey,

I know this issue is closed, but I've been dealing with the same problem. I've got the same setup, and the form is not showing up. The content is displaying as expected, but I get the error as mentioned above.

Is there an update to this?

**Comment by ncphillips** [comment] 2020-01-14 13:27
No updates. I haven't been able to reproduce this issue. If could link to a public repository where this is happening or provide steps to reproduce I can take another look @jarodpeachey

One thing to note is that `useJsonForm` no longer registers the form with the CMS. You should be using `useLocalJsonForm`.

**Comment by mdarrik** [comment] 2020-01-20 06:04
I'm having this issue as well on Windows. I can clone the `gatsby-starter-tina-grande` and run gatsby develop. Nothing shows up to edit the `pages` in that starter. 

I tested in WSL, and the hook was working correctly.

**Comment by jarodpeachey** [comment] 2020-01-20 13:13
@mdarrik This might be a Windows-specific issue... I can't see why, but I've got a coworker who can edit all the Json forms, using the same repo that I can't. He's on Linux.

**Comment by ncphillips** [comment] 2020-01-22 15:06
Hey @SamuelVera the fix for this has been published! Update all your tinacms dependencies and you should be good to go 😄

**Comment by kendallstrautman** [comment] 2020-02-17 23:58
Closing as this is stale, feel free to reopen if the issue persists!

**Closed by kendallstrautman** 2020-02-17 23:58 UTC
Labels: bug
