### ISSUE TITLE
Inline Code doesn't persist on save. 

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2407] opened 2022-01-07 15:40 UTC
## Description

When working with inline code with the rich-text editor, on save the backticks don't persist to the document causing styling to be remove. 

### Steps to reproduce

https://user-images.githubusercontent.com/45409975/148567945-744ef2e4-fdce-40de-a13c-0eeef29b0935.mp4

**Comment by Enigmatical** [comment] 2022-01-07 16:05
I believe @jeffsee55 has a branch/PR that has quite a few MDX fixes and this is among them (ran into the same thing when I was working the `inject-tailwind` feature).

**Comment by Enigmatical** [comment] 2022-01-07 16:10
I'm also going to relate all of these issues as they all relate to `code` in MDX:
https://github.com/tinacms/tinacms/issues/2391
https://github.com/tinacms/tinacms/issues/2390

**Comment by logan-anderson** [comment] 2022-01-07 16:39
I believe this is a duplicate of https://github.com/tinacms/tinacms/issues/2339

**Comment by perkinsjr** [comment] 2022-01-07 16:48
It's not a duplicated of #2339 code blocks are one thing, inline code is the other but I believe they all get fixed with those fixes Jeff is working on but want to keep track.

**Comment by perkinsjr** [comment] 2022-01-16 14:38
Confirmed this is fixed with latest.

**Comment by logan-anderson** [comment] 2022-01-24 14:01
Fixed via https://github.com/tinacms/tinacms/pull/2414

**Closed by logan-anderson** 2022-01-24 14:01 UTC
Labels: bug, mdx
