### ISSUE TITLE
Collection templates stopped working after updating from 1.4.6 to 1.5.0

### ISSUE THREAD

**Issue by kslstn** [tinacms/tinacms#3870] opened 2023-04-27 08:36 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

For one collection, I've defined templates [as described in the docs](https://tina.io/docs/reference/templates/#example-using-templates-instead-of-fields).

Tina CMS builds the dev server without error, but when I use the admin to navigate to the collection, it won't load, saying "Looks like there's nothing to edit on this page." I can't create new pages there either.

When I look at the browser I see the following errors:
Uncaught TypeError: fields is undefined [...]
The above error occurred in the <GetCollection> component: [...]

### Reproduction

https://github.com/kslstn/tina-issues/tree/templates

### Steps to reproduce

Update:

dependencies:
- tinacms 1.4.6
+ tinacms 1.5.0

devDependencies:
- @tinacms/cli 1.5.6
+ @tinacms/cli 1.5.7

Then define a template [as described in the docs](https://tina.io/docs/reference/templates/#example-using-templates-instead-of-fields).

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 322.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 112.0.1722.58
    Firefox: 112.0.1
    Safari: 16.4
    Safari Technology Preview: 16.4
  npmPackages:
    @tinacms/cli: ^1.5.7 => 1.5.7 
    tinacms: ^1.5.0 => 1.5.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment] 2023-04-27 13:36
@kslstn I was not able to reproduce this issue but I did notice a couple of other issues.

You can see this video for more info: https://www.loom.com/share/d28ec20d43f94f22a243953aa028ccc8

**Comment by kslstn** [comment] 2023-04-27 19:14
Hi Logan, thank you for the detailed follow-up. In my tina-issues repo, the templates now work too. I wish it were the case for our real site too. I tried a fresh install and bit by bit I introduced my settings, but it still fails with the templates. I will try again tomorrow.

**Comment by HenrySkup** [comment] 2023-04-28 06:52
I'm also noticing an issue with a collection that uses templates. I'm getting a pop up with :

`[Error] GetCollection failed: Unable to fetch, errors: Error querying file content/consciousCollective/3f3eb861a3d5202fe75bec4c349e96fa06d43dcf.mdx from collection consciousCollective. Please run "tinacms audit" or add the --verbose option for more info`

seems like an auto generated file?

**Comment by appinteractive** [comment] 2023-04-28 09:13
My Folder Structure looks like that:

./content
└── pages
    ├── aktivitaeten
    │   ├── gsr-medienportal
    │   │   ├── blog
    │   │   ├── grenzenlos-vernetzt
    │   │   ├── news.oder.fake
    │   │   └── support-your-crowd
    │   ├── kampagnen-musikvideos
    │   │   ├── anderssein-vereint
    │   │   └── inklusions-und-friedenskampagnensong
    │   ├── musikunterricht-workshops-coaching
    │   │   ├── musikunterricht-fuer-hoergeschaedigte
    │   │   └── workshops-seminare-vortraege
    │   ├── netzwerk-und-oeffentlichkeitsarbeit
    │   │   └── interdisziplinaere-kulturarbeit
    │   └── projekte-und-veranstaltungen
    │       ├── celebrate-the-music
    │       ├── grenzen-sind-relativ-festivals
    │       ├── interdisziplinaere-kulturarbeit
    │       ├── kooperationsprojekte
    │       └── veranstaltungsformate-fuer-dein-event
    ├── media
    │   ├── blog
    │   └── pressespiegel
    ├── ueber-uns
    │   └── das-team
    │       ├── aktionsbuero
    │       ├── beirat
    │       ├── filmproduktion
    │       ├── streetteam
    │       └── vorstand
    └── unterstuetzen

**Comment by appinteractive** [comment] 2023-04-28 09:16
So @HenrySkup it were the templates for you? Sadly, I need them

**Comment by appinteractive** [comment] 2023-04-28 09:22
Tried to remove the templates and only use fields for testing, sadly it does not work. Pages is rendered but admin crashes

<img width="432" alt="grafik" src="https://user-images.githubusercontent.com/432828/235109255-d509ed2e-2369-472c-b66a-096aec96c9e2.png">

**Comment by appinteractive** [comment] 2023-04-28 09:30
Okay now it works (without templates) on my other collections too. Used the template's field also for single templates to be more flexible in the future.

**Comment by logan-anderson** [comment] 2023-04-28 13:58
@HenrySkup, @appinteractive  or @kslstn  Are any of your repos that you are seeing this in public by any chance? (Or if your comfortable, temporarily give me access ?)

Or is there anyway you could produced a reproduction repo?

I am not able to reproduce this at this time.

**Comment by pbougie** [comment] 2023-04-28 16:13
@logan-anderson I have a similar problem and can reproduce it. My current collection settings include:

```
path: "_src",
match: {
  include: "*/pages/*",
},
```

These settings no longer work. This is needed to pickup folders `_src/en/pages/*.md` and `_src/fr/pages/*.md`. However, if I change the settings to (only half my documents are listed):

```
path: "_src/en/pages",
```

Then it works as expected.

**Comment by kslstn** [comment] 2023-04-28 16:41
Hi @logan-anderson, pbougie's solution didn't work for me. I've just invited you to our website's repo (kslstn/fortomorrow-website).

**Comment by logan-anderson** [comment] 2023-04-28 17:43
@kslstn and @appinteractive  I have a [PR  pushed up](https://github.com/tinacms/tinacms/pull/3879) for the `can read property find of undefined issue`

**Comment by logan-anderson** [comment] 2023-04-28 17:49
@pbougie Can you describe the issue you are seeing and how to reproduce it? I don't see any issues in the admin interface.

**Comment by logan-anderson** [comment] 2023-05-01 12:06
@kslstn @appinteractive @pbougie @HenrySkup Both of these issues should be fixed now. Please let us know if it is still happening on the latest version

**Closed by logan-anderson** 2023-05-01 12:06 UTC
Labels: bug

**Comment by pbougie** [comment] 2023-05-01 13:37
@logan-anderson I'm still getting an error but a different one. The first page now loads but when I select a subfolder, I get this error `can't access property "breadcrumbs", document2._sys is undefined`.

<img width="420" alt="Screenshot 2023-05-01 at 09 22 19" src="https://user-images.githubusercontent.com/58460/235457730-a644dcc9-3b60-4429-948b-23c643a3939e.png">

I'm having difficulty reproducing it in a test project however. I have encountered another bug in my test project. Once going through a couple of folders, the documents don't load:

<img width="975" alt="Screenshot 2023-05-01 at 09 29 06" src="https://user-images.githubusercontent.com/58460/235458446-39df8bec-4fb7-4b71-bf45-2b6320814a07.png">

To reproduce:
1. Clone `https://github.com/pbougie/tinacms-20230419`
1. `yarn install` and `yarn dev`
1. Go to *Blog Posts*
1. Select folders until you hit documents
1. Select a document

Is there a way to disable the folders?

**Comment by kldavis4** [comment] 2023-05-01 13:51
@pbougie taking a look at this now

**Comment by kldavis4** [comment] 2023-05-01 14:35
I don't think the issue in your test project is related to the breadcrumbs error. 

I was able to fix that one by doing the following:

1. Rename pages/posts/[slug].js -> pages/posts/[...slug].js
2. Change the mapping in getStaticPaths to: `return { params: { slug: x.node._sys.relativePath.split('/') } };`
3. Change the relativePath in getStaticProps to: `relativePath: ctx.params.slug.join('/'),`
4. Update the ui.router property on the post collection in `tina/config.js` to: `ui: { router: ({ document }) => { return `/posts/${document._sys.relativePath}`; }, },`

Any other details on the project with the breadcrumbs error would be helpful in determining the issue (you can also invite me to the github repository if it is private `kldavis4`)

**Comment by kldavis4** [comment] 2023-05-01 15:03
@pbougie do you have anywhere in your tina/config.js where there is a `_sys.breadcrumbs` (most likely in a ui.router)?

**Comment by kldavis4** [comment] 2023-05-01 15:38
@pbougie ok, I'm happy to take a look if you want to invite me to your project. Otherwise I'll need a reproduction

**Comment by pbougie** [comment] 2023-05-01 17:32
@kldavis4 Ok I've managed to reproduce it:

1. Clone repo: https://github.com/pbougie/tinacms-20230501
1. `npm install`
1. `npm run dev`
1. Go to `http://localhost:8080/admin/`
1. Select *Pages* section
1. Select `en` or `fr`

**Comment by kldavis4** [comment] 2023-05-01 17:35
@pbougie great - taking a look now

**Comment by kldavis4** [comment] 2023-05-01 17:53
@pbougie did you intend to disable create/delete for the pages collection?

**Comment by pbougie** [comment] 2023-05-01 17:56
@kldavis4 Yes, they're a fixed number in my actual project.

**Comment by kldavis4** [comment] 2023-05-01 17:57
@pbougie ok - sounds good. I've found and fixed the issue. Thanks for the reproduction. I'll let you know once it is released

**Comment by pbougie** [comment] 2023-05-01 18:00
@kldavis4 Great news, thanks.

**Comment by appinteractive** [comment] 2023-05-02 16:47
Works thanks 👍

**Comment by pbougie** [comment] 2023-05-02 22:51
@kldavis4 Thanks.
