### ISSUE TITLE
issues editing MDX file with single container components

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2580] opened 2022-02-11 15:38 UTC
## Description

When I have an mdx file like this:

```mdx
<SlidePage>

#22

</SlidePage>
```

and I go to edit it in Tina, I am unable to change any content outside of the `SlidePage` component. This happens when there is a single component in the MDX file.

https://www.loom.com/share/f5c0d974849d4f42bf8c4de34821fa70

### Steps to reproduce

```
export default defineSchema({
  collections: [
    {
      label: "Slides",
      name: "slides",
      format: "mdx",
      path: "content/slides",
      fields: [
        {
          label: "Body",
          name: "body",
          isBody: true,
          type: "rich-text",
          templates: [
            {
              name: "SlidePage",
              label: "Slide Page",
              fields: [
                {
                  type: "string",
                  name: "next",
                  label: "next",
                },
             ]
           }]
         }]
         }]
         })
```

Repo: https://github.com/jamespohalloran/next-mdx-deck

If there is already content outside of the main component when I load the page in Tina, there is no issues:

```mdx

# This will work fine

<SlidePage>

# test

</SlidePage>
```

When I delete that single component, I also get a bunch of errors and can no longer edit:

<img width="1449" alt="Screen Shot 2022-02-11 at 11 37 48 AM" src="https://user-images.githubusercontent.com/3323181/153621381-fb4aa7ee-73d1-4d8c-9d39-c70ef95a9e83.png">

#### Tinacms Package Versions

├── @tinacms/cli@0.60.5
├── tinacms@0.66.3

**Comment by jeffsee55** [comment] 2022-10-25 22:51
Trying to reproduce this and it seems to be fixed. Closing but reopen if necessary.

**Closed by jeffsee55** 2022-10-25 22:51 UTC
Labels: bug, mdx
