### ISSUE TITLE
Markdown lists and blockquotes should be allowed inside blockquotes

### ISSUE THREAD

**Issue by johnridesabike** [tinacms/tinacms#3492] opened 2022-12-31 23:39 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

The Tina Markdown editor is not able to parse this:

```md
Paragraph

> Quoted paragraph
>
> * Quoted list
> * Quoted list
>
> > Nested quoted paragraph

Paragraph
```

The above is valid Markdown (by every standard I'm aware of). There may be other elements that don't work inside blockquotes, but those were the only two I encountered so far.

This bug may be related to #3118, although this specific issue is a bigger problem for my content.

### Reproduction

https://github.com/johnridesabike/tina-bug-report

### Steps to reproduce

1. Add a markdown page with the above content. (Or view `content/page/quotedlists.mdx` in the example repo)
2. Try to edit it in the Tina editor.
3. The editor will fail to work due to this error:
```
Error parsing markdown
  
UnwrapBlock: Unknown block content of type list
```

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 93.80 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/code/tina-bug-report/my-tina-app/node_modules/.bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    @tinacms/cli: ^1.0.0 => 1.0.0
    tinacms: ^1.0.0 => 1.0.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by mAAdhaTTah** [comment] 2023-01-02 15:27
Duplicate of #3118

**Comment by johnridesabike** [comment] 2023-01-02 16:41
Feel free to close if this is a duplicate 🙂 I saw the other one, but it wasn't obvious to me if it was exactly the same or just similar.

Either way, I'm glad it's on your radar! I'm migrating a Forestry site that uses a lot of block content inside of blockquotes, so this was one of the first issues I ran into.

**Comment by mAAdhaTTah** [comment] 2023-01-02 16:57
To be clear, I don't work for Forestry or anything, I'm just an outside contributor who ran into the same issue :).

**Comment by jeffsee55** [comment] 2023-01-02 23:34
Will close this in favor of the other one, thanks for additional input!

**Closed by jeffsee55** 2023-01-02 23:34 UTC
Labels: bug
