### ISSUE TITLE
Deleting or renaming a page causes a GraphQL error in Local Mode

### ISSUE THREAD

**Issue by jerefrer** [tinacms/tinacms#4150] opened 2023-08-17 08:28 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi there,

When I delete or rename a page **in Local Mode** the whole admin section goes down :
![Capture d’écran (45)](https://github.com/tinacms/tinacms/assets/140954/debdd040-2878-4e38-bb59-8f885ab0c689)

With this error in the console:
````
GraphQLError [Object]: Unable to find record content/Tagazok.md
   at Database.get (E:\Programming\songtsen\node_modules\.pnpm\@tinacms+graphql@1.4.22_react@18.2.0\node_modules\@tinacms\graphql\dist\index.js:5110:17)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   at async Resolver.getDocumentOrDirectory (E:\Programming\songtsen\node_modules\.pnpm\@tinacms+graphql@1.4.22_react@18.2.0\node_modules\@tinacms\graphql\dist\index.js:4323:23)
   at async E:\Programming\songtsen\node_modules\.pnpm\@tinacms+graphql@1.4.22_react@18.2.0\node_modules\@tinacms\graphql\dist\index.js:5587:26
   at async sequential (E:\Programming\songtsen\node_modules\.pnpm\@tinacms+graphql@1.4.22_react@18.2.0\node_modules\@tinacms\graphql\dist\index.js:78:18)
   at async Database.query (E:\Programming\songtsen\node_modules\.pnpm\@tinacms+graphql@1.4.22_react@18.2.0\node_modules\@tinacms\graphql\dist\index.js:5585:16)
   at async Resolver.resolveCollectionConnection (E:\Programming\songtsen\node_modules\.pnpm\@tinacms+graphql@1.4.22_react@18.2.0\node_modules\@tinacms\graphql\dist\index.js:4688:22)
   at async Promise.all (index 4)
   at async Promise.all (index 0)
   at async resolve (E:\Programming\songtsen\node_modules\.pnpm\@tinacms+graphql@1.4.22_react@18.2.0\node_modules\@tinacms\graphql\dist\index.js:4853:17)
   at async E:\Programming\songtsen\node_modules\.pnpm\@tinacms+cli@1.5.26_@babel+core@7.22.9_react@18.2.0\node_modules\@tinacms\cli\dist\index.js:1211:26
Error querying file content/Tagazok.md from collection post. Please run "tinacms audit" or add the --verbose option  for more info
GraphQL request:8:11
8 |           documents(sort: $sort, after: $after, first: $limit, filter: $filter,
  |           ^
  | folder: $folder) @include(if: $includeDocuments) {
````

I thought this started to happen when I enabled the Tina Search feature, but now even when I disable it the problem continues to happen, so now I'm now so sure about it being related to the search.

This has already been mentioned in this discussion: https://github.com/tinacms/tinacms/discussions/4143, but I thought I'd created a proper issue about it with more details.

Here's my Tina config file for my Hugo project, in which I don't think I did anything special:

````
import { defineConfig } from "tinacms";

// Your hosting provider likely exposes this as an environment variable
const branch = process.env.HEAD || process.env.VERCEL_GIT_COMMIT_REF || "gh-pages";

export default defineConfig({
  branch,
  clientId: "...", // Get this from tina.io
  token: "...", // Get this from tina.io

  build: {
    outputFolder: "admin",
    publicFolder: "static",
  },
  media: {
    tina: {
      mediaRoot: "",
      publicFolder: "static",
    },
  },
  search: {
    tina: {
      indexerToken: '...',
      stopwordLanguages: ['eng']
    },
    indexBatchSize: 100,
    maxSearchIndexFieldLength: 100
  },
  schema: {
    collections: [
      {
        name: "post",
        label: "Posts",
        path: "content/",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          {
            type: "image",
            name: "featured",
            label: "Background image",
          },
          {
            type: "rich-text",
            name: "body",
            label: "Body",
            isBody: true,
          },
        ],
      },
      {
        name: "event",
        label: "Events",
        path: "content/chanteloube/events",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          {
            type: "datetime",
            name: "start_date",
            label: "Begins on",
          },
          {
            type: "datetime",
            name: "end_date",
            label: "Ends on",
          },
          {
            type: "rich-text",
            name: "body",
            label: "Body",
            isBody: true,
          },
        ],
      },
    ],
  },
});
````

### Reproduction

https://github.com/jerefrer/songtsen-hugo/

### Steps to reproduce

1. Create a post
2. Delete or Rename the post
3. See the whole admin becoming unusable, with this error: ![Capture d’écran (45)](https://github.com/tinacms/tinacms/assets/140954/debdd040-2878-4e38-bb59-8f885ab0c689)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
    Memory: 7.83 GB / 15.89 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\.yarn\bin\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.10 - C:\ProgramData\chocolatey\bin\pnpm.EXE
  Browsers:
    Chrome: 115.0.5790.171
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @tinacms/cli: ^1.5.26 => 1.5.26
    tinacms: ^1.5.17 => 1.5.17
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment] 2023-08-17 12:32
Hey, thanks for filling out a report. I'm not able to reproduce on your linked repo. Might I be doing something differently?
https://www.loom.com/share/dc50115244e64fd69555aa664bc15625?sid=15c2eea0-24e9-4133-818a-1411b888aae6

**Comment by jerefrer** [comment] 2023-08-17 13:57
Nope, that's precisely what I'm doing to trigger the bug ... Could it be platform related? Like specific to Windows or my version of node or something?

**Comment by kldavis4** [comment] 2023-08-17 17:47
possible a duplicate of #4018

**Comment by iFrogHop2Worlds** [comment] 2023-08-19 21:43
Seems like it might be a windows thing. I am also on windows. Seems like grphql not reindexing properly in deletion of collections. If I restart the server its fine again.

**Comment by jamespohalloran** [comment] 2023-08-21 12:39
All the recent cases I've seen of this seem to be on Windows, so I think @kldavis4 is right. Closing in favour of #4018

**Closed by jamespohalloran** 2023-08-21 12:39 UTC
Labels: bug
