### ISSUE TITLE
GraphQL error when a reference field references two collection types

### ISSUE THREAD

**Issue by adiba** [tinacms/tinacms#3157] opened 2022-09-08 12:02 UTC
## Description

When two collection types that share a common field name are referenced from a field of type `reference`, we get a GraphQL error.

### Steps to reproduce

Create a barebones starter and choose NPM. Add the following to the top of `collections` in `.tina/schema.js`:
```javascript
    {
      label: "Test",
      name: "test",
      path: "content/test",
      fields: [
        {
          name: "test",
          label: "Test",
          type: "reference",
          collections: ["page", "post"]
        },
      ],
    },
```

Do `npm run dev`.

### Expected result

Compile without error.

### Actual result

```
Error 0: GraphQLDocumentError: Fields "body" conflict because they return conflicting types "JSON" and "String". Use different aliases on the fields to fetch both if this was intentional.
```

#### Tinacms Package Versions
```text
tinacms@0.69.2
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |     N/A    |
| os      |     Windows 10 1909   |
| node    |     v16.17.0    |
| npm     |     8.18.0    |

**Comment by jeffsee55** [comment] 2022-09-15 21:07
This is a duplicate of https://github.com/tinacms/tinacms/issues/3150

**Closed by jeffsee55** 2022-09-15 21:07 UTC
Labels: bug
