### ISSUE TITLE
datetime field not saved

### ISSUE THREAD

**Issue by danielknell** [tinacms/tinacms#3053] opened 2022-07-25 22:11 UTC
## Description

date field not saved unless edited, despite being pre-populated and required.

### Steps to reproduce

given the following schema

```ts
const schema = defineSchema({
  collections: [
    {
      label: "Posts",
      name: "post",
      path: "content/posts",
      format: "mdx",
      fields: [
        {
          type: "string",
          label: "Title",
          name: "title",
          isTitle: true,
          required: true,
        },
        {
          type: "datetime",
          label: "Date",
          name: "date",
          required: true,
        },
        {
          type: "rich-text",
          label: "Body",
          name: "body",
          isBody: true,
        },
      ],
    },
  ],
  config: {
    media: {
      tina: {
        publicFolder: "public",
        mediaRoot: "uploads",
      },
    },
  },
});
```

- create a new post
- the UI pre populates the date field with todays date
- add "blah" in the filename and title field only
- press save

### Expected result

What should happen?

`content/posts/blah.mdx` should be created with a `date` field or form should refuse to submit.

### Actual result

form submits, file is created without actually setting the date.

which then breaks the graphql server with the following as the value isn't set.

```
Cannot return null for non-nullable field Post.date.

GraphQL request:33:3
32 |   title
33 |   date
   |   ^
More error context below
Cannot return null for non-nullable field Post.date.
Error: Cannot return null for non-nullable field Post.date.
    at completeValue (/workspaces/blog/node_modules/graphql/execution/execute.js:559:13)
    at /workspaces/blog/node_modules/graphql/execution/execute.js:469:16
    at async Promise.all (index 3)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Object.resolve (/workspaces/blog/node_modules/@tinacms/graphql/dist/index.js:24706:17)
    at async /workspaces/blog/node_modules/@tinacms/cli/dist/index.js:246:24 {
  locations: [ { line: 33, column: 3 } ],
  path: [ 'postConnection', 'edges', 0, 'node', 'date' ]
}
Warning: There was an error when fetching data
Error: Unable to fetch, errors: 
        Cannot return null for non-nullable field Post.date.
    at TinaClient.request (/workspaces/blog/node_modules/tinacms/dist/client.js:69:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requester (webpack-internal:///./.tina/__generated__/types.ts:355:20)
    at async getStaticPaths (webpack-internal:///./src/pages/blog/[slug].tsx:52:21)
    at async Object.buildStaticPaths (/workspaces/blog/node_modules/next/dist/build/utils.js:487:31)
```

### Environment

nextjs/typescript

#### Tinacms Package Versions

```text
├── @tinacms/cli@0.60.28
├── react-tinacms-editor@0.53.26
├── tinacms@0.68.13
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | safari |
| os      | macOS |
| node    | v18.4.0 |
| yarn     | 1.22.19 |

# failing scenarios:

- create post without clicking in the field and save
- create post, click the field, then save

# passing scenarios:

- click the field and then select a date , then save

**Comment by jeffsee55** [comment] 2022-07-25 22:15
Related to https://github.com/tinacms/tinacms/issues/2694

**Comment by jamespohalloran** [comment] 2022-07-25 22:22
Thanks for the thorough bug report! But does seem like a duplicate of #2694. Closing to keep the thread all in one place

**Closed by jamespohalloran** 2022-07-25 22:22 UTC
Labels: bug, duplicate
