### ISSUE TITLE
WYSIWYG toolbar in sidebar editor jumps to top of page when scrolling 

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#758] opened 2020-02-14 18:16 UTC
## Description
https://www.loom.com/share/0376dae8696849f8ba1a62ad5def7a8c

### Expected result
When scrolling inside the body of the page, the sidebar shouldn't be affected

#### Tools

| Tool    | Version |
| ------- | ------- |
| Chrome |         |
| iOS      |         |

**Comment by spbyrne** [comment] 2020-02-14 18:40
This is addressed by PR #661 once merged. It requires some additional work (passing sticky=false when in sidebar as mentioned in the PR, which is why it's still a draft). Otherwise it fixes a number of issues.

**Comment by spbyrne** [comment] 2020-02-14 18:41
[Mentioned here as well.](https://github.com/tinacms/tinacms/pull/713#issuecomment-582286884)

**Comment by kendallstrautman** [comment] 2020-02-17 23:46
This is a duplicate of #618. Closing

**Closed by kendallstrautman** 2020-02-17 23:46 UTC
Labels: bug, has-pull-request, ux
