### ISSUE TITLE
Replace all instances of using `index` in an array maps in React renders with truly unique values

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1630] opened 2020-11-20 02:01 UTC
## Description

We use iteration indices as `key`'s in our react renders it quite a few places (or we don't provide a key altogether).

This is not ideal for React, because React uses the `key` to de-dupe DOM updates, and _all_ keys invalidate in an array if you re-order the array and use the indices as your `key`.

Considering, everywhere we use map we should be:

- Providing a `key` on the top level JSX element
- Creating the key by hashing the item being iterated to guarantee a unique, persistent key as long as that item doesn't mutate

### Steps to reproduce

```
const toIterate =  [1,2,3];

export const IterateFail = () => {
  return (
    <ul>
      {toIterate.map((item, index) => (
        <li key={index}>{item}</li>
      )}
    </ul>
  ));
}
```

Now if I reorder `toIterate` by adding `[0,1,2,3]` or by removing `[0, 1]` react will re-render everything.

We can improve this by passing a truly unique value that is not dependant on the array order.

E.g, using a hash function to hash the data of the map.

```
import stringHash from "string-hash";

const JSONSafeStringify = (input: any): string => {
  let cache = [];
  const result = JSON.stringify(input, (key, value) => {
    if (typeof value !== "object" || value === null) {
      return value;
    }
    if (cache.includes(value)) {
      // Circular reference found, discard key
      return undefined;
    }
    // Store value in our collection
    cache.push(value);
    return value;
  });
  cache = null; // Enable garbage collection
  return result;
};

const hash = (obj) => {
  if (!obj) return 0;
  return typeof obj !== "string"
    ? stringHash(JSONSafeStringify(obj))
    : stringHash(obj);
};

const toIterate =  [1,2,3];

export const IterateWin = () => {
  return (
    <ul>
      {toIterate.map((item, index) => (
        <li key={stringHash(item)}>{item}</li>
      )}
    </ul>
  ));
}
```

Now re-orders effect _order_ of each item the DOM but not _rendering_ of the contents of any item.

### Expected result

Re-orders (e.g, in inline blocks) shouldn't trigger a re-render of the whole list.

### Actual result

Re-orders (e.g, in inline blocks) shouldn't trigger a re-render of the whole list.

#### Tinacms Package Versions
N/A (for NDA reasons)

**Comment by dwalkr** [comment] 2020-11-23 15:33
This issue is a bit over-broad IMO. The "steps to reproduce" section here demonstrates a principle in React but doesn't actually demonstrate any behavior in the TinaCMS code.

I realize using indices as keys is technically incorrect, but in some places that's the only identifier we have (hence the moderately complex solution you've proposed as the most reasonable alternative.) In some cases (though not likely for inline blocks,) a "dumb" re-render might be cheaper than serializing the object tree.

Additionally, I don't think "it unnecessarily triggers a re-render" is enough of a symptom to act on. End users won't notice re-renders unless (/until) it starts tanking framerates.

I'm closing this issue because "various parts of the codebase are not idiomatic" is not something we can or should tackle right now. If you believe this issue is causing a specific problem in a Tina implementation, I encourage you to post again!

**Comment by chrisdmacrae** [comment] 2020-11-23 21:25
@dwalkr to be more specific, any field implementation in Tina that handles arrays of anything is a problem, where we use index as a key.

Any re-order of this array has react lose its mind.

For example, in large Inline Blocks or Group lists, this can take seconds to propagate the result of the re-render, because it re-renders _every_ child in the DOM.

**Comment by kendallstrautman** [comment] 2020-11-23 22:25
Yeah we can change the [key for `InlineBlock`](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx#L175) to be `blockName` or something, since blocks _do_ get re-ordered we should change this. If you can identify other specific instances of where index is being used as the key, we can fix as necessary.

**Comment by kendallstrautman** [comment] 2020-11-23 22:25
This issue is broad though, let's trackdown the specific places where we need to make changes.

**Comment by chrisdmacrae** [comment] 2020-11-23 22:39
@kendallstrautman @dwalkr totally agree. The reframing of this should be: fix any instance where an end-user (developer) or their end-user (editor) can manipulate or re-order the array. 

The most obvious offenders are any fields (inline or not) that can manipulate arrays.

**Comment by dwalkr** [comment] 2020-11-24 01:51
"Fix any instance..." is still an unhelpful framing, particularly for a bug report. 

I genuinely appreciate the legwork in identifying the likely culprit of **what I imagine to be a bug you are experiencing in a Tina implementation,** but an issue that requests us to _make the code look like X anywhere it currently looks like Y_ is not very useful on its own. There is (I'm assuming) a _real problem_ here, but it's stated so indirectly that I would struggle to evaluate the quality of a solution intended to address it.

Practically speaking, if there are areas of the codebase with poor `key` prop handling that don't have a noticeable impact on the functioning/performance of Tina, I don't think it's important to fix them.

**Closed** 2020-11-24 02:06 UTC
Labels: bug
