### ISSUE TITLE
Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by TomSmedley** [tinacms/tinacms#2769] opened 2022-04-02 10:49 UTC
## Description

I've followed the methods to add Tina to a NextJS project. Visiting http://localhost:3000/demo/blog/HelloWorld gives a runtime error.

### Steps to reproduce

1. `npx create-next-app@latest`
2. `npx @tinacms/cli@latest init`
3. Apply the `<Tina>` wrapper.
4. Visit http://localhost:3000/demo/blog/HelloWorld

![image](https://user-images.githubusercontent.com/95056193/161379767-e9e98d8f-92f7-4653-b4fd-5cc40b045472.png)

#### Tinacms Package Versions
```text
├── @tinacms/cli@0.60.9
├── autoprefixer@10.4.4
├── eslint-config-next@12.1.4
├── eslint@8.12.0
├── framer-motion@6.2.8
├── next@12.1.4
├── postcss@8.4.12
├── prettier-plugin-tailwindcss@0.1.8
├── react-dom@18.0.0
├── react@18.0.0
├── styled-components@5.3.5
├── tailwindcss@3.0.23
└── tinacms@0.66.9
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Chrome |
| os      | Windows 11 |
| node    | 16.14.2 |
| npm     | 8.5.5 |

**Comment by jamespohalloran** [comment] 2022-08-04 17:20
Closing for now, if it's still an issue and can be reproduced we'll revisit

**Closed by jamespohalloran** 2022-08-04 17:20 UTC
Labels: bug, react-18

**Comment by genox** [comment] 2022-10-20 13:39
I have the same error here on a new project that uses themeui and tina. Is there any setup code that tina requires in terms of styling? Or things one needs to consider when using a css-in-js solution with tina?

**Comment by jamespohalloran** [comment] 2022-10-20 13:53
> I have the same error here on a new project that uses themeui and tina. Is there any setup code that tina requires in terms of styling? Or things one needs to consider when using a css-in-js solution with tina?

Upon looking at this again, it looks like React18 was likely the original source of this issue (We have an open ticket for that here: https://github.com/tinacms/tinacms/issues/3067). Are you on React 18, @genox ?

We have some upcoming changes to the way that Tina is run that will circumvent this issue. 
We have the docs/migration-post in this preview-deployment if you want to try it out early: https://tinacms-site-next-git-feat-iframe-docs-tinacms.vercel.app/blog/upgrading-to-iframe/

**Comment by genox** [comment] 2022-10-20 23:43
That's correct, I use React 18. I will try your suggestion, thanks!

**Comment by genox** [comment] 2022-10-21 06:38
Just migrated my project according to the guide you posted. Managed to get it to start, here's some findings:

- ``permanent` is not set to `true` or `false` for route {"source":"/admin","destination":"/admin/index.html"` - got this error after adding the redirect. the `permanent` prop needs to be set on the route def.
- I use a symlink to store tina schema code inside of a folder that can be managed by my CLI. Had to make sure all tina code uses relative imports, as the root tsconfig is no longer being used (I use it for shortcut imports).

And here is an issue that I don't seem to be able to solve right now: I can "launch" the admin interface but contextual editing doesn't work anymore: "Looks like there's nothing to edit on this page". Links to open the content URL from within the admin file browser work fine, tho.
