### ISSUE TITLE
Date picker defaults to today, however it sends null down to the markdown

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2736] opened 2022-03-25 19:17 UTC
When using the Tina Date picker, it will auto select to today. This however is returned as null. 

We should have the Date picker either not default to today or actually send today's date.

**Comment by jamespohalloran** [comment] 2022-06-06 15:55
duplicate of https://github.com/tinacms/tinacms/issues/2694

**Closed by jamespohalloran** 2022-06-06 15:55 UTC
Labels: bug, duplicate
