### ISSUE TITLE
Error on build deploying to GitLab Pages

### ISSUE THREAD

**Issue by phikai** [tinacms/tinacms#516] opened 2019-12-04 14:00 UTC
## Description

I've setup the Quick Start project from https://tinacms.org/docs/gatsby/quickstart which seems to work fine locally. I then followed the steps from Gatsby to deploy to GitLab pages: https://www.gatsbyjs.org/docs/deploying-to-gitlab-pages/

There is a an error during the build here:

```
error Building static HTML failed
104   129 |  * `Layout` component is rendered in the site.
105   130 |  */
106 > 131 | export default withPlugin(Layout, CreatePostPlugin)
107       |                           ^
108   132 | 
109   WebpackError: TypeError: Object(...) is not a function
```

Output available in the pipeline here: https://gitlab.com/phikai/pages-gatsby-tina/-/jobs/369223510

Project located here: https://gitlab.com/phikai/pages-gatsby-tina

### Steps to reproduce

Setup the TinaCMS quickstart and then follow the Gastby guide for GitLab pages.

### Expected result

The GitLab CI job should complete and the project should deploy to pages (with or without Tina).

### Actual result

Pipeline fails with the error above

**Comment by dwalkr** [comment] 2019-12-16 15:06
Hi @phikai , it looks like this was caused by a minor compatibility break that occurred when we simplified import paths. I have opened a PR to your project with the fix for this: https://gitlab.com/phikai/pages-gatsby-tina/merge_requests/1

One thing contributing to this issue could be that the project has a `yarn.lock` file but not a `package-lock.json`. Since your CI script is using NPM and not Yarn, this can lead to your builds being non-reproducible and fetching newer versions of packages in CI than you had tested with locally. Either switching your CI script to use Yarn, or using NPM locally instead and generating a `package-lock.json` can help avoid these kinds of suprises going forward.

Of course, we don't plan to make a habit of breaking compatibility with existing projects, but we're still pretty early stage here and trying to make future-oriented decisions. Thanks for being patient with us!

**Closed by dwalkr** 2019-12-16 15:06 UTC
Labels: bug
