### ISSUE TITLE
Admin visual editing does not work with a Remix project deployment on Cloudflare

### ISSUE THREAD

**Issue by meetdave3** [tinacms/tinacms#4373] opened 2023-11-27 18:51 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I'm trying to use Tina CMS in a newly scaffolded Remix app and hosting it on Cloudflare Workers / Pages (tried both deployment methods). 

Everything in the admin works as expected apart from the visual editing where the following error shows up in the production deployment right after going to https://remix-tina-worker.pages.dev/admin/#/~
![Screenshot 2023-11-27 at 19 38 23](https://github.com/tinacms/tinacms/assets/15693697/94bbeed3-fcde-4f16-9450-6dce9ba9ccb8)

This error appears when running it locally, 
![Screenshot 2023-11-27 at 19 38 57](https://github.com/tinacms/tinacms/assets/15693697/bddeb3d6-47d2-4431-be9e-e0410e66619f)

The complete error line reads: 
`useLocation() may be used only in the context of a <Router> component.
`

Here's a snapshot from the console: 
![Screenshot 2023-11-27 at 19 40 37](https://github.com/tinacms/tinacms/assets/15693697/92ab896b-89f2-4d31-a2b8-bb5807c1bbb3)

Deployment URL: https://remix-tina-worker.pages.dev/
Github Repo: https://github.com/meetdave3/remix-tina-worker

### Reproduction

https://github.com/meetdave3/remix-tina-worker

### Steps to reproduce

1. Create a new project using `npm create cloudflare@latest my-remix-app -- --framework=remix`
2. Follow the steps on https://tina.io/docs/frameworks/remix/

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 126.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - ~/Shell/remix-tina-worker/node_modules/.bin/yarn
    npm: 10.2.3 - /opt/homebrew/bin/npm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Edge: 115.0.1901.188
    Safari: 16.1
  npmPackages:
    @tinacms/cli: ^1.5.36 => 1.5.36 
    tinacms: ^1.5.26 => 1.5.26
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment] 2023-11-27 19:14
Hello @meetdave3!

Seems to be a dependency issue. 

If I pull down your repo and install with yarn everything works as expected. 
If I install with npm then I get this error.

Not sure what the underlying cause is but I will take a closer look.

**Comment by jeffsee55** [comment] 2023-11-27 23:17
@logan-anderson I think this can be resolved by deduping `react-router-dom` https://github.com/tinacms/tinacms/blob/b85c53d6dee36d09a07fc16ddd650b5de85c756f/packages/%40tinacms/cli/src/next/vite/index.ts#L188

**Comment by silouanwright** [comment] 2024-01-06 21:56
I ran into the same issue with this Remix template

https://github.com/kiliman/remix-vite-template
![CleanShot 2024-01-06 at 15 55 03@2x](https://github.com/tinacms/tinacms/assets/708820/aadd829e-b40c-45ee-ba97-2b7415e372d9)

I used npm with this, but I also tried installing yarn and installing the dependencies that way, but that didn't work either.

**Comment by silouanwright** [comment] 2024-01-06 22:16
I can confirm @jeffsee55 's solution that by going into `node_modules/@tinacms/cli/dist/index.js` and adding `react-router-dom` to the dedupe array on line 977 that it functions correctly.

**Comment by benistary** [comment] 2024-01-16 22:49
I ran into same error with nextjs 14

**Comment by HelmerBarcos** [comment] 2024-03-08 19:31
I was also experiencing this issue while trying to configure Visual Editing for a Docusaurus 3.1 project.

While TinaCMS requires `"react-router-dom": "6.3.0"`, Docusaurus seems to depend on another version of `react-router-dom`

Installing `react-router-dom@6.3.0` using npm solved the problem for me without needing to edit the `tinacms/packages/@tinacms/cli/src/next/vite/index.ts` file.

**Comment by dantman** [comment] 2024-05-29 21:49
In Remix projects, the original issue that was opened, the remix-router-dom dependency comes from remix-run. So directly installing an older version of react-router-dom probably won't work and it's probably not good for remix-run if you even could.

A better workaround would likely be to force tinacms to use a newer version of react-router-dom. The current version `6.23.1` is still of the same major version as the `6.3.0` that tinacms is using. The newer version should still work with TinaCMS, so I don't really understand why tinacms is pinning a specific version when react-router-dom is the kind of thing that can break from having multiple instances in the same tree.

Make sure you first figure out what the newest version of react-router-dom in your tree is. Like so:

```
$ npm list react-router-dom
├─┬ @remix-run/react@2.9.2
│ └── react-router-dom@6.23.1
├─┬ @tinacms/cli@1.5.45
│ └─┬ @tinacms/app@1.2.41
│   └── react-router-dom@6.3.0
└─┬ tinacms@1.6.3
  └── react-router-dom@6.3.0
```

For `npm`, overrides can be added to force all react-router-dom dependencies to use the same version. Make sure to put whatever version your framework is currently using in the override. If you're not using `npm` look up the documentation for whatever package manager you are using. e.g. Yarn has a [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) option instead.

```json
	"overrides": {
		"react-router-dom": "6.23.1"
	},
```

**Closed** 2024-12-13 02:57 UTC
Labels: bug, wontfix
