### ISSUE TITLE
Image upload isn't reflected after the first time

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#271] opened 2019-10-09 15:06 UTC
## Description

After starting the Gatsby server, dragging an image to the image field only works the first time. All subsequent uploads will not be reflected in the Tina preview and in the site (although the file uploads to the project correctly).  

### Steps to reproduce
1. Start gatsby server
2. try to add image to image field in tina
3. try a second time
4. NOTE: try typing and your image will show up

### Expected result
n/a
### Actual result
n/a
### Environment

```
 "@tinacms/gatsby-plugin-tinacms": "0.1.3",
    "@tinacms/gatsby-tinacms-git": "0.2.0",
    "@tinacms/react-tinacms-remark": "0.2.3",
```

**Comment by scottgallant** [comment] 2019-11-12 03:45
I believe this is no longer an issue. Can someone confirm?

**Comment by kendallstrautman** [comment] 2019-11-12 18:38
Yes I can't reproduce this. Closing for now.

**Closed by kendallstrautman** 2019-11-12 18:38 UTC
Labels: bug
