### ISSUE TITLE
Rename a file after saving.

### ISSUE THREAD

**Issue by matt-antone** [tinacms/tinacms#2991] opened 2022-06-15 20:39 UTC
## Summary

A lot of the Frameworks support a "slug" for changing a post's path. 

Implementing slugs across multiple JAMStack platforms sounds like a pain. If Tina could rename the file, it would achieve the same thing as a "slug".

### Expected Results

A field or button for changing the filename. 

### Notes

We don't do ongoing SEO at our Agency, but our clients often hire SEO specialists and the "slug" is something they always change and tune. This allows the user to correct a misspelled path or tune their SEO by changing the it.

**Comment by jamespohalloran** [comment] 2022-06-20 13:10
Closing, as I believe this is a duplicate of https://github.com/tinacms/tinacms/issues/1978

**Closed by jamespohalloran** 2022-06-20 13:10 UTC
Labels: duplicate, enhancement, NEEDS POINTS
