### ISSUE TITLE
Visual bug stops buttons working in the side bar / admin

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2806] opened 2022-04-14 13:24 UTC
## Description

I am working with Sols digital and there is a bug it seems with some of the buttons. I tested this on a fresh nextjs app where I added Tina. You can see in the video the buttons don't do anything when clicked

### Steps to reproduce

1. Create a new React 18 project
2. Add Tina 
3. Try clicking the buttons in the sidebar

Here is an example

![example](https://res.cloudinary.com/forestry-demo/video/upload/v1649942978/Kapture_2022-04-13_at_09.24.43.gif)

### Expected result

Buttons should work.

**Comment by perkinsjr** [comment] 2022-04-14 13:31
This could be related to React strict mode...

**Comment by perkinsjr** [comment] 2022-04-14 13:33
Setting 
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
}

module.exports = nextConfig
```

Fixes the bug

**Comment by Enigmatical** [comment] 2022-04-14 16:11
This appears to be caused by `react` 18.0.0 or `react-dom` 18.0.0.  Switching back to `17.0.2` fixes the problem. 😓

**Comment by logan-anderson** [comment] 2022-04-14 16:17
Looks like it might be [related to this](https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors)

**Comment by logan-anderson** [comment] 2022-04-14 17:05
Going to take a look at this to see if its something that can easily be fixed.

**Comment by jeffsee55** [comment] 2022-04-15 00:21
I tried reproducing this in the monorepo, and having upgraded Yarn, Next _and_ React I have a lot of things yelling at me. Most obvious is an invalid hook call warning right when I start the app: `Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:...`. I'm assuming this is related to monorepo issues because I haven't seen others mention it (plus it's a common issue in monorepos). But at the same time, I'm able to reproduce a similar enough error to what's described that it seems like the actual issue could be related to React context.

Instead of the button just not working, I get this error: 

> `Error: Unable to find `TinaProvider`; did you forget to add the TinaCMS container to your app root?  See our setup docs: https://tina.io/docs/introduction/tina-init/#adding-tina`

And after searching through the logic in that button, I see that it mounts a component which is using context from `'@tinacms/sharedctx'`, https://github.com/tinacms/tinacms/blob/a8abf8eb42abb57406f2cc8e245517bdffc35ef0/packages/@tinacms/toolkit/src/packages/react-sidebar/components/Nav.tsx#L60. Stubbing out `setEdit` fixes things for me.

So it seems like 

```
@tinacms/toolkit --------> @tinacms/sharedctx
tinacms/edit-state ------> @tinacms/sharedctx
```
Are not getting the same contexts. Will dig in more next week, branch is [here](https://github.com/tinacms/tinacms/pull/2813), part of upgrading to Yarn 3 for reasons not directly related to this issue.

**Comment by jeffsee55** [comment] 2022-04-19 16:16
We may have some things conflicting here, but this seems related https://github.com/tailwindlabs/headlessui/issues/681. Which is closed by https://github.com/tailwindlabs/headlessui/pull/1326

**Comment by raphaeltm** [comment] 2022-04-21 20:31
This also seems to affect the menu button on content items. With `reactStrictMode: true` they do not work, but when it's turned off, they do:

![image](https://user-images.githubusercontent.com/910895/164547307-d68ae141-0f30-4de6-87ff-b190055cd9b2.png)

**Comment by raphaeltm** [comment] 2022-04-21 20:41
This also affected the font size/format button. Disabling strict mode fixed that as well.

![image](https://user-images.githubusercontent.com/910895/164548920-6a34a6e2-276c-490c-b1bf-112fc7f7c5fd.png)

**Comment by logan-anderson** [comment] 2022-04-27 14:06
@raphaeltm  i just tested this with the following package.json and it was working for me. Can you make sure you are on the latest version of `tinacms` and `@tinacms/cli` 

```json
{
  "name": "test-logan-1",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "tinacms server:start -c \"next dev\"",
    "build": "tinacms server:start -c \"next build\"",
    "start": "tinacms server:start -c \"next start\"",
    "lint": "next lint"
  },
  "dependencies": {
    "@tinacms/cli": "^0.60.12",
    "next": "12.1.5",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "styled-components": "^5.3.5",
    "tinacms": "^0.67.3"
  },
  "devDependencies": {
    "eslint": "8.13.0",
    "eslint-config-next": "12.1.5"
  }
}

```
This issue might be happening because of a bug in `headlessui`. Can you make sure you are **not** using an older version (maybe an older version is cached somewhere). Here are a couple things that you might want to try.

- delete `node_modules` and re-install
- make sure there is not any old version in your `yarn.lock`
- update other dependencies that also depend on `headlessui`  

Please let us know if you still cant fix it.

**Comment by logan-anderson** [comment] 2022-05-02 17:34
Going to close for now. Please let us know this remains an issue for you.

**Closed by logan-anderson** 2022-05-02 17:34 UTC
Labels: bug, 2 points
