### ISSUE TITLE
Can not save bold text

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2340] opened 2021-12-09 14:29 UTC
If you add a title, then a quote and then bold text, the bold text will not save as bold.

see https://www.loom.com/share/0e0a04d8bd1c4d0e8511155e5fe912a9

**Comment by Perni1984** [comment] 2021-12-13 19:24
@logan-anderson I believe this is a duplicate of https://github.com/tinacms/tinacms/issues/2323 which should be fixed in the latest main.

**Closed** 2022-01-05 23:41 UTC
Labels: bug, mdx
