### ISSUE TITLE
Error fetching media

### ISSUE THREAD

**Issue by huco95** [tinacms/tinacms#3254] opened 2022-10-05 14:52 UTC
## Description

I can not access media.
![image](https://user-images.githubusercontent.com/2738365/194090278-f8073f14-e857-4648-925e-e98bc098088d.png)
![image](https://user-images.githubusercontent.com/2738365/194090998-d3b3f9b7-fd55-4846-b2f1-67c73b515cb2.png)

### Steps to reproduce

Repo: https://github.com/huco95/raquel-nogal-next
1. Clone repo
2. Publish to vercel (as this only happens on production not on local dev server)

### Expected result
Media panel should be opened to upload images.

### Actual result
![image](https://user-images.githubusercontent.com/2738365/194090278-f8073f14-e857-4648-925e-e98bc098088d.png)

### Environment
Vercel deployment.

#### Tinacms Package Versions
```text
"@tinacms/cli": "^0.61.20"
"tinacms": "^0.69.14"
```

**Comment by kldavis4** [comment] 2022-10-05 15:59
Can you provide more information on what actions you are taking? Are you just opening the media manager and getting this error or doing something else? The reason I ask is because the url in the log doesn't really make sense: `/list//blog/images/?limit=20`

I think you would need to navigate into a subfolder (/blog/images/) in order for that url to be requested

**Comment by huco95** [comment] 2022-10-05 17:36
> Can you provide more information on what actions you are taking? Are you just opening the media manager and getting this error or doing something else? The reason I ask is because the url in the log doesn't really make sense: `/list//blog/images/?limit=20`
> 
> I think you would need to navigate into a subfolder (/blog/images/) in order for that url to be requested


I just open the media manager and get this error. This is working fine on localhost, so I think the schema configuration is correct.

**Comment by kldavis4** [comment] 2022-10-05 17:48
I forked your repo and deployed it to vercel and I'm currently unable to reproduce this.

@logan-anderson any idea why his media manager would be attempting to list `/blog/images/` when it first opens?

**Comment by huco95** [comment] 2022-10-05 19:30
This is the behavior when I am trying to create a new post:
![error1](https://user-images.githubusercontent.com/2738365/194146045-695ccfb1-7749-483f-877a-757831d335d3.gif)

This from the Media Manager:
![error2](https://user-images.githubusercontent.com/2738365/194146113-7cf9abc8-67d1-45cf-aec5-7a9a5f41fe02.gif)

**Comment by kldavis4** [comment] 2022-10-05 19:43
Great, that helps a lot. This line is the problem: https://github.com/kldavis4/raquel-nogal-next/blob/main/.tina/schema.js#L46

Remove that uploadDir prop and I think it will resolve the issue.

**Comment by kldavis4** [comment] 2022-10-06 21:27
It looks like there is a bug that is causing this. Fix should be released in the next day or two (or you can use the tinacms@beta version)

**Comment by huco95** [comment] 2022-10-06 21:33
> It looks like there is a bug that is causing this. Fix should be released in the next day or two (or you can use the tinacms@beta version)

Great! Thanks for the quick fix! ❤️

**Closed** 2022-10-14 14:15 UTC
Labels: bug
