### ISSUE TITLE
Tina CMS makes changes MDX without typing in the form

### ISSUE THREAD

**Issue by AGMETEOR** [tinacms/tinacms#1098] opened 2020-05-05 17:22 UTC
## Description

- Tina CMS automatically makes changes to the MDX files and changes information

Accompanying issues
- Changes the format of the date in frontmatter
- Adds quotes to authors in frontmatter

### Steps to reproduce
Open an page using a template that has tina cms integrated using the `useLocalMdxForm` hook.
Look at the git changes e.g. in vs code

### Expected result
No changes should happen to mdx files before I type in the sidebar form

### Actual result
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28563179/81095533-d2ab2600-8f0d-11ea-89cc-db7da8da9fe1.gif)

### Environment
Chrome browser
Gatsby
gatsby-novela-theme

#### Tinacms Package Versions

```text
├─┬ gatsby-plugin-tinacms@0.1.34
│ └─┬ tinacms@0.19.0
│   ├── @tinacms/alerts@0.1.2
│   ├── @tinacms/core@0.7.4
│   ├─┬ @tinacms/fields@0.10.0
│   ├─┬ @tinacms/form-builder@0.3.2
│   ├─┬ @tinacms/forms@0.4.1
│   ├── @tinacms/icons@0.9.0
│   ├── @tinacms/media@0.1.0
│   ├── @tinacms/react-alerts@0.1.2
│   ├─┬ @tinacms/react-core@0.2.11
│   ├─┬ @tinacms/react-forms@0.1.2
│   ├── @tinacms/react-modals@0.1.2
│   ├── @tinacms/react-screens@0.1.1
│   ├─┬ @tinacms/react-sidebar@0.1.2
│   ├─┬ @tinacms/react-toolbar@0.1.0
│   ├── @tinacms/styles@0.4.2
│   └─┬ react-tinacms-editor@0.5.0
│     ├─┬ @tinacms/react-forms@0.1.2-alpha.0
├─┬ gatsby-tinacms-git@0.4.8
│ ├─┬ @tinacms/api-git@0.7.0
│ └── @tinacms/git-client@0.6.7

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |       Google Chrome  |
| os      |     MacOS High Sierra    |
| node    |   v10.20.1      |
| npm     |     6.14.4    |

**Comment by kendallstrautman** [comment] 2020-05-14 15:24
Duplicate of #146, this isn't something we can fix at this time.

**Closed** 2020-05-14 15:24 UTC
Labels: bug, wontfix

**Comment by AGMETEOR** [comment] 2020-05-14 21:43
@kendallstrautman I have seen the duplicate issue. Mind sharing why it's not fixable.

**Comment by kendallstrautman** [comment] 2020-05-14 21:59
@ncphillips can speak more to this but my guess is a final form stuff? 

My overarching understanding of why we wouldn't fix this is because the added quote formatting doesn't actually break or change the frontmatter values. And presumably this formatting change just happens the first time content is edited with Tina. 

For the date issue, when your using the date field in Tina it needs to use the date object, so that object needs to be stored in the frontmatter value and formatting the final output of that date object should happen in the component responsible for rendering the date value.

**Comment by kendallstrautman** [comment] 2020-05-14 22:10
I made a [new issue](https://github.com/tinacms/tinacms/issues/1140) to frame this as an enhancement request. This new proposal wouldn't address the actual formatting changes themselves but would prevent these changes from occurring until the editor actually instigates form changes.
