### ISSUE TITLE
Tina Markdown fails when there is markdown comments

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#3521] opened 2023-01-17 15:23 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When using the rich text editor, add a comment. An error message will pop up and wont let you edit the document until the comment is removed.
 

### Reproduction

https://www.loom.com/share/c1a666e16ea44500b0b6718acfda8373

### Steps to reproduce

See video.
https://www.loom.com/share/c1a666e16ea44500b0b6718acfda8373

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 957.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/dev/tinacms/tinacms.org/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.01.02.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 109.0.5414.87
    Firefox: 101.0.1
    Safari: 15.6.1
  npmPackages:
    @tinacms/auth: ^1.0.0 => 1.0.0 
    @tinacms/cli: ^1.0.6 => 1.0.6 
    @tinacms/datalayer:  0.2.3 
    @tinacms/graphql:  0.60.0 
    tinacms: ^1.1.3 => 1.1.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment] 2023-01-23 15:56
I believe this is a duplicate of: https://github.com/tinacms/tinacms/issues/3213

**Closed by jamespohalloran** 2023-01-23 15:56 UTC
Labels: bug
