### ISSUE TITLE
useTina returns empty data on initial load of NextJs nested catch-all page 

### ISSUE THREAD

**Issue by DmacMcgreg** [tinacms/tinacms#3212] opened 2022-09-20 16:35 UTC
## Description

Data returned from getStaticProps is correct. All the data is returned from the client.queries api on the server side. The queries are passed to the useTina client correctly. However, the useTina hook returns empty data. The strange thing is that this is only on the initial page load when refreshing the page. Once navigating to another page and returning back by clicking a nextjs link, the data loads fine. The tina sidebar also is unable to fetch the editing context. I've verified that the relativePath is being passed correctly to useTina in the variables, and the query itself is the same regardless... 

### Steps to reproduce

1. Create catch-all page as such: 'app/pages/impacts/[[...impacts]].tsx'
2. get data in getStaticProps client.queries
3. pass ...tinaProps within the props to the page 
4. verify the data is correctly in the props to the page, along with the variables and the query
5. notice that useTina will return blank data.
6. (you can even see the page flash the initial render with the server data, but goes blank after useTina returns blank
7. click another link to another tina page (and probably any other non-tina page also would replicate this)
8. go back to the page (click a link back to the page)
9. it will load the data from tina fine now, and will load the editing context in sidebar

### Expected result

useTina should return the data when refreshing the page, or typing into address bar

### Actual result

useTina returns blank

#### Tinacms Package Versions

```
├── @tinacms/cli@0.61.8
├── next-tinacms-cloudinary@3.4.3
├── tinacms@0.69.7

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Chrome 105      |
| os      |   MacOS12      |
| node    |      16.3.0   |
| npm     |     8.1.0    |

**Comment by logan-anderson** [comment] 2022-09-21 18:14
👋 @DmacMcgreg thanks for the report. I am not able to replicate this. You can see a video below of me going directly to the page and the tina data loading fine.

https://www.loom.com/share/e9ac5d6dcfe14ea6964c661c3a4e4348

It might be an issue with your app. Do you mind re-creating this issue with the "basic starter" ( can be generated from `npx create-tina-app@latest` and then selecting "basic starter" ) and pushing it up to an open source repo so we can take a look? 

Thanks 😄

**Comment by jamespohalloran** [comment] 2022-10-14 14:19
Closing this for now as we are unable to reproduce. If this is still an issue for you @DmacMcgreg, and you're able to provide more info, we can re-open!

**Closed by jamespohalloran** 2022-10-14 14:19 UTC
Labels: bug

**Comment by DmacMcgreg** [comment] 2022-10-14 14:34
Thanks @jamespohalloran 
I wasn't given the budget at work to try to dig in further since the client halted the project. If I get some free time I'll try to figure out the issue on this!

Cheers!
