### ISSUE TITLE
Can't save empty array of blocks

### ISSUE THREAD

**Issue by mbrain-io** [tinacms/tinacms#3918] opened 2023-05-08 07:16 UTC
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I cant save empty array of blocks. I think video is enough to understand the problem, but if necessary I can create a demo repo.

https://user-images.githubusercontent.com/86771348/236759289-5cb47aeb-77b0-4e7c-8335-4e840c810139.mov

### Reproduction

https://github.com/

### Steps to reproduce

I have this field defined:

```
{
    type: 'object',
    name: 'header',
    label: 'Header',
    list: true,
    ui: {
        component: 'blocks',
    },
    templates: [
        example1,
        example2,
    ],
},
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 36.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - ~/Sites/mbrain/node_modules/.bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.63
    Firefox: 107.0
    Safari: 16.4
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment] 2023-05-12 14:27
@mbrain-io What version of TinaCMS are you on? I am not able to re-produce this on the latest version.

**Comment by mbrain-io** [comment] 2023-05-12 14:36
@logan-anderson I am on tinacms@1.5.1

**Comment by logan-anderson** [comment] 2023-05-12 14:42
@mbrain-io I am not seeing this issue on the latest versions of tiancms and @tinacms/cli. Can you try updating?

**Comment by mbrain-io** [comment] 2023-05-12 17:34
Updated to v1.5.5 and seeing the same issue...

This is the schema for the field in question:

```
{
    name: 'headerBlocks',
    type: 'object',
    label: 'Header',
    list: true,
    ui: {
        component: 'blocks',
        visualSelector: true,
        validate: (value: any[], allValues: any[], meta: any, field: any) => {
            if (value && value.length > 1) {
                return 'Max 1 item';
            }
        },
    },
    templates: [
        emptyTemplate,
        header1Template,
        header2Template,
    ],
},
```

**Comment by logan-anderson** [comment] 2023-05-15 13:36
@mbrain-io Just wanted confirm that you also updated @tinacms/cli? I am not able to reproduce with pretty much the same schema. (See video)

https://www.loom.com/share/95af07e466914fdc87c9834ccf653e88

Is your repo public? If not can, you create a reproduction? 

Thanks 😄

**Comment by mbrain-io** [comment] 2023-05-19 19:03
@logan-anderson I created new demo project and still having the same issue ☹️ 

[Here it is](https://github.com/mbrain-io/tina-issue-3918)

Try editing single post document, "Field 1" is blocks field. First add several blocks and save. Then try to remove all blocks and save, and after reload old blocks will reappear.

![Screenshot 2023-05-19 at 9 03 18 PM](https://github.com/tinacms/tinacms/assets/86771348/0cb16959-62c3-47f9-91c6-b354b227b01a)

**Comment by logan-anderson** [comment] 2023-05-19 20:18
> @logan-anderson I created new demo project and still having the same issue ☹️
> 
> [Here it is](https://github.com/mbrain-io/tina-issue-3918)
> 
> Try editing post document, "Field 1" is blocks field. First add several blocks and save. Then try to remove all blocks and save, and after reload old blocks will reappear.
> 
> ![Screenshot 2023-05-19 at 9 03 18 PM](https://user-images.githubusercontent.com/86771348/239614649-0cb16959-62c3-47f9-91c6-b354b227b01a.jpg)

I was able to reproduce it in your repo (Thanks for that 😄 ) but when I copied the same config into the monorepo I could not reproduce. Will take a closer look after the weekend.

**Comment by mbrain-io** [comment] 2023-05-23 19:09
@logan-anderson Just tried it, and yes, same problem exists when saving with Tina Cloud

**Comment by logan-anderson** [comment] 2023-05-24 15:15
@mbrain-io to provide an update: 
I have tried copying the exact project into the mono repo (same code and version of next, React, etc) and I am still unable to reproduce the issue in the mono repo. This makes me think it _could_ be a dependency issue. I tried pinning some of the deps without any luck. Ill update you when more progress is made.

**Comment by mbrain-io** [comment] 2023-05-24 16:14
@logan-anderson Thanx for the update. Interesting, I am also using Turborepo on other projects and did not have this type of issue. I guess this is important to solve, cause if your monorepo setup is not reflecting the fresh NextJS+Tina installation then it cant be used for testing right?

Btw which monorepo workspace/package exactly are you using for testing?

**Comment by logan-anderson** [comment] 2023-05-24 16:47
@mbrain-io When I say "The monorepo" I am talking about the [tinacms monorepo](https://github.com/tinacms/tinacms) it uses pnpm and turbopack.  For testing I created a new folder in the examples folder and then copied all the files from your reproduction into it. After that I changed all the tinacms deps to be "workspace:*". 

Then ran `pnpm install`  and `pnpm watch`from the root. After that (in a new terminal), I changed the directory into the newly created one and ran `pnpm dev`

**Comment by mbrain-io** [comment] 2023-05-24 19:08
@logan-anderson I tried what you described and yes, it works correctly! It seems that running examples from monorepo is not the same as running exactly the same code as a standalone. Never encountered this to be honest 🤔 and yes it smells like monorepo is resolving to different dependencies somehow... Or maybe published Tina code is not the same as the one in the monorepo?

**Comment by mbrain-io** [comment] 2023-05-24 19:34
@logan-anderson Yes, it seems that published Tina code is not the same as the one in monorepo. I replaced public Tina packages with monorepo versions:

```
"@tinacms/cli": "file:///Users/mbrain/Sites/tinacms-main/packages/@tinacms/cli",
"tinacms": "file:///Users/mbrain/Sites/tinacms-main/packages/tinacms",
```

And it worked correctly from my repo! I guess with next Tina version this will be solved 😀

**Comment by mbrain-io** [comment] 2023-09-22 06:15
@logan-anderson This issue still exists in tinacms@1.5.20

**Comment by logan-anderson** [comment] 2023-09-22 14:36
@jeffsee55 I know you worked on a similar issue. Was this one fixed as well?

**Comment by jeffsee55** [comment] 2023-09-22 18:04
Should be fixed by this when it lands resolve-legacy-fields

**Closed** 2023-10-30 16:34 UTC
Labels: bug
