### ISSUE TITLE
Error occurred prerendering page

### ISSUE THREAD

**Issue by loleg** [tinacms/tinacms#4176] opened 2023-08-31 20:38 UTC
It is not possible to complete a production build - while dev builds are working fine _on exactly the same code base!_ - due to a build error that looks like this:

```
- info Checking validity of types  
- info Creating an optimized production build  
- info Compiled successfully
- info Collecting page data  
[  ==] - info Generating static pages (14/32)
Error occurred prerendering page "/posts". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Unable to fetch, please see our FAQ for more information: https://tina.io/docs/errors/faq/

        Errors: 
	Error querying file content/program/Sonntag---Workshops.mdx from collection program. Please run "tinacms audit" or add the --verbose option  for more info
    at TinaClient.request (file:///.../node_modules/tinacms/dist/client.mjs:40:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requester (/.../.next/server/chunks/970.js:642:22)
    at async getStaticProps (/.../.next/server/pages/programs.js:245:23)
- info Generating static pages (32/32)

> Export encountered errors on following paths:
	/posts
```

The file being referred to indeed does not exist, and there are no links to it. Tina Cloud has been updated with this Graph, we tried Reindexing and Refreshing Webhooks. We have tried cleaning and rebuilding locally. Even after restoring the file we get this error! It seems our `main` branch is just stuck with this missing static page.

I have not seen other Tina users complain of this, but there are very similar looking issues in Next.js. In fact, I get the same error when I type:

`npx next build --no-lint`

See also:

- [next export - StackOverflow](https://stackoverflow.com/questions/72497719/next-export-gives-me-an-error-occurred-prerendering-page)
- [how to fix nextjs prerender error - vercel deployment?](https://stackoverflow.com/questions/70345435/how-to-fix-nextjs-prerender-error-vercel-deployment)
- [NextJS Prerender Error - Works fine in Dev, breaks in Build](https://stackoverflow.com/questions/71002100/nextjs-prerender-error-works-fine-in-dev-breaks-in-build)

### Reproduction

https://github.com/playbern/www-playbern-ch/commit/17b971164c7c40a7160552b9eb4092e6047b98ff

### Steps to reproduce

Create an `.mdx` file for a blog post, publish it, then delete it.

I am able to reproduce this on my local machine with a (`yarn build`) and Vercel.

### System Info

```shell
System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 PRO 5675U with Radeon Graphics
    Memory: 4.35 GB / 14.46 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nave/installed/18.17.1/bin/node
    Yarn: 1.22.19 - ~/Localdev/PlayBern/www-playbern-ch/node_modules/.bin/yarn
    npm: 9.6.7 - ~/.nave/installed/18.17.1/bin/npm
  Browsers:
    Chromium: 116.0.5845.110
  npmPackages:
    @tinacms/cli: ^1.5.25 => 1.5.28 
    tinacms: ^1.5.20 => 1.5.19
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment] 2023-08-31 21:17
I forked your site and it built successfully. Created a file and deleted it and rebuilt the site without issue. 

Can you provide more detailed steps to reproduce? I or maybe create a https://loom.com/

**Comment by loleg** [comment] 2023-08-31 21:30
Thanks for testing @kldavis4  

I think you would need to build with my TOKEN and CLIENT_ID to replicate with the stuck Cloud configuration. Please write me a private message if you want to do that.

I've created a new Tina.io account and moved the site there. This has solved the problem for me for now. So I am closing this issue as this is a reasonable workaround, and hopefully just a rare glitch in the graph.

**Comment by kldavis4** [comment] 2023-08-31 21:32
@loleg let's figure out what's going on :) you can share the client id here (it's not sensitive)

**Comment by loleg** [comment] 2023-08-31 21:34
Sure - it's just our dev site, and can be rotated:

```
TINA_PUBLIC_CLIENT_ID=b022fb78-dee7-41fa-8081-1869fa876097
TINA_TOKEN=da79e74cff63ddfd9081cd8951e12a5067d02e40
```

**Comment by kldavis4** [comment] 2023-08-31 21:44
It is building successfully with your site credentials (I can't login to your site so I'm not able to add / remove files). If this is still happening, please record a video showing all the steps so we can investigate further.

**Comment by loleg** [comment] 2023-08-31 22:09
Like I said, after I switched to a new set of credentials, the problem was gone. When I switch back to the credentials above, the problem does **not** return ...

Since neither of us is able to reproduce the problem, I guess we can close the issue!

In lieu of a screencast where I type the build command, here are a couple of screenshots:

![Screenshot from 2023-08-30 17-20-10](https://github.com/tinacms/tinacms/assets/31819/b8a81640-eca3-4b6e-a9e4-d857c144c8e5)

![](https://user-images.githubusercontent.com/31819/264478501-054cee9c-1c58-43e4-9fde-56cab27adae2.png)

![image](https://github.com/tinacms/tinacms/assets/31819/b5888fb4-0943-44fe-be07-1d8c4211dd3f)

**Comment by kldavis4** [comment] 2023-08-31 22:12
You stated that it happened after adding/removing a post, right? That's the piece that I am requesting more details about.

**Comment by loleg** [comment] 2023-09-01 06:16
Yes, we believe that is what happened - at least, I'm pretty sure this happened after a series of content changes and nothing major happening in the code. As soon as we have more details, we will share them.

**Comment by jamespohalloran** [comment] 2023-11-29 02:29
Sounds like we're unable to reproduce this, so closing until we have more details

**Closed by jamespohalloran** 2023-11-29 02:29 UTC
Labels: bug

**Comment by loleg** [comment] 2023-11-29 09:55
That's fine, thanks.
