### ISSUE TITLE
Scrolling issues with inline editing

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#772] opened 2020-02-19 16:39 UTC
```gherkin
Given I have a long content
When I'm inline-editing my content
Then sometimes editor scrolls to top
```

Reproduced on the current `master` branch when using the demo-gatsby package.

Also reported by @PaulBunker on Slack.

**Comment by PaulBunker** [comment] 2020-02-24 10:28
## New information that might help finding the cause

So...
I've removed the wysiwyg from my page and replaced it with a custom textarea field.
I have smooth-scrolling on the document enabled.
When I edited text, the page would scroll from the top down to the cursor.
_I fixed this by disabling the smooth-scrolling while in edit mode. I get the scrollbar flashing as I type but I can live with this **for now**_

## hypothesis

The contents of the textarea is being removed then replaced by final form leading to the cursor jumping to the top of the screen and the page scrolls with it as the text is replaced and the cursor returned **magically to the right place 🤷🏼‍♂️** the page scrolls the cursor into view.

I still think the other [issue](https://github.com/tinacms/tinacms/issues/735) is related but I don't think this is a WYSIWYM issue I think its a final form problem perhaps

**Comment by employee451** [comment] 2020-03-05 08:22
I'm also having this issue.
I've made a [CodeSandbox](https://codesandbox.io/s/bold-smoke-mvou1?fontsize=14&hidenavigation=1&theme=dark) to demonstrate.

**Comment by ncphillips** [comment] 2020-03-11 16:15
[Fixed in this week's release](https://tinacms.org/blog/2020-03-09-release-notes)

**Closed by ncphillips** 2020-03-11 16:15 UTC
Labels: bug, ux
