### ISSUE TITLE
404 error when building project if branch name contains /

### ISSUE THREAD

**Issue by pharmarin** [tinacms/tinacms#3207] opened 2022-09-17 05:59 UTC
## Description

I am getting a 404 error when I build my project, in the step "Generating static pages"

### Steps to reproduce

My branch name contains a "/", I tried with another branch name and it worked. 

### Actual result

What actually happened?

#### Tinacms Package Versions

```text
├── @tinacms/cli@0.61.13
├── tinacms@0.69.7
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by psirenny** [comment] 2022-09-27 13:56
I just encountered this one as well.

**Comment by jamespohalloran** [comment] 2022-10-14 18:12
I wasn't able to reproduce this. Just tried a slash in a branchname in the tina-cloud-starter, and the build ran fine: https://github.com/tinacms/tina-cloud-starter/pull/353

**Comment by jamespohalloran** [comment] 2022-10-27 17:11
Closing as we can't reproduce. If it continues to be an issue, we can re-open

**Closed by jamespohalloran** 2022-10-27 17:11 UTC
Labels: bug
